from gym_minigrid.envs.empty import *
from gym_minigrid.envs.doorkey import *
from gym_minigrid.envs.multiroom import *
from gym_minigrid.envs.fetch import *
from gym_minigrid.envs.gotoobject import *
from gym_minigrid.envs.gotodoor import *
from gym_minigrid.envs.putnear import *
from gym_minigrid.envs.lockedroom import *
from gym_minigrid.envs.playground_v0 import *
from gym_minigrid.envs.roomgrid import *
from gym_minigrid.envs.unsafeenvironment import *
