from gym_minigrid.envs.empty import *
from gym_minigrid.envs.doorkey import *
from gym_minigrid.envs.multiroom import *
from gym_minigrid.envs.fetch import *
from gym_minigrid.envs.gotoobject import *
from gym_minigrid.envs.gotodoor import *
from gym_minigrid.envs.putnear import *
from gym_minigrid.envs.lockedroom import *
from gym_minigrid.envs.keycorridor import *
from gym_minigrid.envs.unlock import *
from gym_minigrid.envs.unlockpickup import *
from gym_minigrid.envs.blockedunlockpickup import *
from gym_minigrid.envs.playground_v0 import *
from gym_minigrid.envs.redbluedoors import *
from gym_minigrid.envs.obstructedmaze import *
from gym_minigrid.envs.memory import *
from gym_minigrid.envs.fourrooms import *
from gym_minigrid.envs.crossing import *
from gym_minigrid.envs.lavagap import *
from gym_minigrid.envs.dynamicobstacles import *
from gym_minigrid.envs.distshift import *
